server:
  port: 8081

spring:
  profiles:
    include: git
  main:
    banner-mode: 'off'
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LittleBaiBai/myapp-config-test.git
          search-paths: sub
  security:
    oauth2:
      client:
        registration:
          uaa:
            provider: uaa
            client-id: dashboard_client
            client-secret: dashboard_secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authentication-method: basic
            scope: openid
        provider:
          uaa:
            token-uri: ${uaa.token-uri}
            authorization-uri: ${uaa.url}/oauth/authorize
            jwk-set-uri: ${uaa.jwk-set-uri}
            user-info-uri: ${uaa.url}/userinfo
            user-name-attribute: user_name
      resourceserver:
        jwt:
          issuer-uri: ${uaa.url}/oauth/token

uaa:
  url: http://localhost:8080/uaa
  token-uri: ${uaa.url}/oauth/token
  jwk-set-uri: ${uaa.url}/token_keys

scs:
  credhub:
    path: /some-credhub-path/foobar
  config-server:
    service-instance-id: ${SPRING_CLOUD_APPBROKER_SERVICE_INSTANCE_ID}